#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:

#check if the required parameters where passed 
if [ $# -lt 4 ]; then
 echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
 # Assign the parameters to a variable
 file_path=$1
 server_ip=$2
 username=$3
 ssh_key=$4

 # transfer file using scp
 scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:"~
fi
