#!/usr/bin/env bash
# Install nginx web server

# Install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Configuration: configure nginx to listen on port 80
ufw allow 'Nginx HTTP'
#mkdir /etc/nginx/html

# create an html sample page for the site
echo "Hello World!" > /var/www/html/index.html

# creating server block file
#echo "server {
#        listen 80 default_server;
#       listen [::]:80 default_server;
#
#        root /etc/nginx/html;
#        index index.html index.htm index.nginx-debian.html;
#
#        server_name _;
#}
#" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx start
