#!/usr/bin/env bash
# Install nginx web server

# Install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Configuration
mkdir /etc/nginx/html

# create an html sample page for the site
echo "Hello World!" > /etc/nginx/html/index.html

# creating server block file
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /etc/nginx/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
}
" > /etc/nginx/sites-available/default

# Restart Nginx
nginx -s reload
