#!/usr/bin/env bash
# Bash script that displays Best School 10 times using while loop

i=1
while [ "$i" -le 20 ]
do
	if [ $i -eq 4 ]
	then
		echo $i
		echo "bad luck from china"
	elif [ $i -eq 9 ]
	then
		echo $i
		echo "bad luck from Japan "
	elif [ $i -eq 17 ]
	then
		echo $i
		echo "bad luck from Italy"
	else
		echo $i
	fi
	((i += 1))
done
